In [139]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [140]:
url = 'https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2020'

In [144]:
requests.get(url)

In [145]:
web = requests.get(url)

In [146]:
body = BeautifulSoup(web.text,'html')
body

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-sticky-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-toc-available" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>Billboard Year-End Hot 100 singles of 2020 - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-sticky-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-toc-available";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy",
"wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"0b38028a-f715-4f3f-b007-b0da35de5f29","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Billboard_Year-End_Hot_100_singles_of_2020","wgTitle":"Billboard Year-End Hot 100 singles of 2020","wgCurRevisionId":1261725476,"wgRevisionId":1261725476,"wgArticleId":66004147,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description with empty Wikidata description","2020 record charts","Lists of Billboard Year-End Hot 100 singles","2020 in American music"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"Billboard_Year-End_Hot_100_singles_of_2020","wgRelevantArticleId":66004147,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true
,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgCiteReferencePreviewsActive":false,"wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":10000,"wgRelatedArticlesCompat":[],"wgEditSubmitButtonLabelPublish":true,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q103827484","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGETopicsMatchModeEnabled":false,
"wgGEStructuredTaskRejectionReasonTextInputEnabled":false,"wgGELevelingUpEnabledForUser":false};RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","jquery.makeCollapsible.styles":"ready","ext.wikimediamessages.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready","ext.wikimediaBadges":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","mediawiki.page.media","site","mediawiki.page.ready","jquery.tablesorter","jquery.makeCollapsible","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","mmv.bootstrap",
"ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.visualEditor.targetLoader","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","ext.checkUser.clientHints","ext.growthExperiments.SuggestedEditSession"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cext.wikimediamessages.styles%7Cjquery.makeCollapsible.styles%7Cjquery.tablesorter.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<meta content="MediaWiki 1.44.0-wmf.8" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/The_Weeknd_%28253662129%29.jpeg/1200px-The_Weeknd_%28253662129%29.jpeg" property="og:image"/>
<meta content="1200" property="og:image:width"/>
<meta content="1800" property="og:image:height"/>
<meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/The_Weeknd_%28253662129%29.jpeg/800px-The_Weeknd_%28253662129%29.jpeg" property="og:image"/>
<meta content="800" property="og:image:width"/>
<meta content="1200" property="og:image:height"/>
<meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/The_Weeknd_%28253662129%29.jpeg/640px-The_Weeknd_%28253662129%29.jpeg" property="og:image"/>
<meta content="640" property="og:image:width"/>
<meta content="960" property="og:image:height"/>
<meta content="width=1120" name="viewport"/>
<meta content="Billboard Year-End Hot 100 singles of 2020 - Wikipedia" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="//upload.wikimedia.org" rel="preconnect"/>
<link href="//en.m.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2020" media="only screen and (max-width: 640px)" rel="alternate"/>
<link href="/w/index.php?title=Billboard_Year-End_Hot_100_singles_of_2020&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
<link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2020" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
<link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch"/>
<link href="login.wikimedia.org" rel="dns-prefetch"/>
</head>
<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-Billboard_Year-End_Hot_100_singles_of_2020 rootpage-Billboard_Year-End_Hot_100_singles_of_2020 skin-vector-2022 action-view"><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
<header class="vector-header mw-header">
<div class="vector-header-start">
<nav aria-label="Site" class="vector-main-menu-landmark">
<div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown">
<input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>
<span class="vector-dropdown-label-text">Main menu</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Main menu</div>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navigation
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a></li><li class="mw-list-item" id="n-contents"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a></li><li class="mw-list-item" id="n-aboutsite"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li class="mw-list-item" id="n-contactpage"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
<div class="vector-menu-heading">
		Contribute
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-help"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li class="mw-list-item" id="n-introduction"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a></li><li class="mw-list-item" id="n-upload"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Main_Page">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/wikipedia.png" width="50"/>
<span class="mw-logo-container skin-invert">
<img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en.svg" style="width: 7.5em; height: 1.125em;"/>
<img alt="The Free Encyclopedia" class="mw-logo-tagline" height="13" src="/static/images/mobile/copyright/wikipedia-tagline-en.svg" style="width: 7.3125em; height: 0.8125em;" width="117"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>
<span>Search</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Search Wikipedia" autocapitalize="sentences" class="cdx-text-input__input" id="searchInput" name="search" placeholder="Search Wikipedia" title="Search Wikipedia [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Special:Search"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Search</button>
</form>
</div>
</div>
</div>
<nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
<div class="vector-user-links-main">
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<nav aria-label="Appearance" class="vector-appearance-landmark">
<div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
<input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label"><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance"></span>
<span class="vector-dropdown-label-text">Appearance</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
</div>
</div>
</div>
</nav>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-sitesupport-2"><a class="" data-mw="interface" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-createaccount-2"><a class="" data-mw="interface" href="/w/index.php?title=Special:CreateAccount&amp;returnto=Billboard+Year-End+Hot+100+singles+of+2020" title="You are encouraged to create an account and log in; however, it is not mandatory"><span>Create account</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-login-2"><a accesskey="o" class="" data-mw="interface" href="/w/index.php?title=Special:UserLogin&amp;returnto=Billboard+Year-End+Hot+100+singles+of+2020" title="You're encouraged to log in; however, it's not mandatory. [o]"><span>Log in</span></a>
</li>
</ul>
</div>
</div>
</div>
<div class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out" id="vector-user-links-dropdown" title="Log in and more options">
<input aria-haspopup="true" aria-label="Personal tools" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-user-links-dropdown" id="vector-user-links-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-user-links-dropdown-checkbox" id="vector-user-links-dropdown-label"><span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>
<span class="vector-dropdown-label-text">Personal tools</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item" id="p-personal" title="User menu">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item" id="pt-sitesupport"><a href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-createaccount"><a href="/w/index.php?title=Special:CreateAccount&amp;returnto=Billboard+Year-End+Hot+100+singles+of+2020" title="You are encouraged to create an account and log in; however, it is not mandatory"><span class="vector-icon mw-ui-icon-userAdd mw-ui-icon-wikimedia-userAdd"></span> <span>Create account</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-login"><a accesskey="o" href="/w/index.php?title=Special:UserLogin&amp;returnto=Billboard+Year-End+Hot+100+singles+of+2020" title="You're encouraged to log in; however, it's not mandatory. [o]"><span class="vector-icon mw-ui-icon-logIn mw-ui-icon-wikimedia-logIn"></span> <span>Log in</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-user-menu-anon-editor" id="p-user-menu-anon-editor">
<div class="vector-menu-heading">
		Pages for logged out editors <a aria-label="Learn more about editing" href="/wiki/Help:Introduction"><span>learn more</span></a>
</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">

In [147]:
body.find('table')
table = body.find('table')
table

<table class="wikitable sortable" style="text-align: center">
<caption>List of songs on <i><a href="/wiki/Billboard_(magazine)" title="Billboard (magazine)">Billboard</a></i><span class="nowrap" style="padding-left:0.1em;">'s</span> 2020 <a href="/wiki/Billboard_Year-End" title="Billboard Year-End">Year-End</a> Hot 100 chart<sup class="reference" id="cite_ref-3"><a href="#cite_note-3"><span class="cite-bracket">[</span>3<span class="cite-bracket">]</span></a></sup>
</caption>
<tbody><tr>
<th scope="col" style="background:#dde;"><abbr title="Number">No.</abbr>
</th>
<th scope="col" style="background:#dde;">Title
</th>
<th scope="col" style="background:#dde;">Artist(s)
</th></tr>
<tr>
<td>1</td>
<td>"<a href="/wiki/Blinding_Lights" title="Blinding Lights">Blinding Lights</a>"</td>
<td><a href="/wiki/The_Weeknd" title="The Weeknd">The Weeknd</a>
</td></tr>
<tr>
<td>2</td>
<td>"<a href="/wiki/Circles_(Post_Malone_song)" title="Circles (Post Malone song)">Circles</a>"</td>
<td><a href="/wiki/Post_Malone" title="Post Malone">Post Malone</a>
</td></tr>
<tr>
<td>3</td>
<td>"<a href="/wiki/The_Box_(Roddy_Ricch_song)" title="The Box (Roddy Ricch song)">The Box</a>"</td>
<td><a href="/wiki/Roddy_Ricch" title="Roddy Ricch">Roddy Ricch</a>
</td></tr>
<tr>
<td>4</td>
<td>"<a href="/wiki/Don%27t_Start_Now" title="Don't Start Now">Don't Start Now</a>"</td>
<td><a href="/wiki/Dua_Lipa" title="Dua Lipa">Dua Lipa</a>
</td></tr>
<tr>
<td>5</td>
<td>"<a href="/wiki/Rockstar_(DaBaby_song)" title="Rockstar (DaBaby song)">Rockstar</a>"</td>
<td><a href="/wiki/DaBaby" title="DaBaby">DaBaby</a> featuring <a href="/wiki/Roddy_Ricch" title="Roddy Ricch">Roddy Ricch</a>
</td></tr>
<tr>
<td>6</td>
<td>"<a href="/wiki/Adore_You_(Harry_Styles_song)" title="Adore You (Harry Styles song)">Adore You</a>"</td>
<td><a href="/wiki/Harry_Styles" title="Harry Styles">Harry Styles</a>
</td></tr>
<tr>
<td>7</td>
<td>"<a href="/wiki/Life_Is_Good_(song)" title="Life Is Good (song)">Life Is Good</a>"</td>
<td><a href="/wiki/Future_(rapper)" title="Future (rapper)">Future</a> featuring <a href="/wiki/Drake_(musician)" title="Drake (musician)">Drake</a>
</td></tr>
<tr>
<td>8</td>
<td>"<a href="/wiki/Memories_(Maroon_5_song)" title="Memories (Maroon 5 song)">Memories</a>"</td>
<td><a href="/wiki/Maroon_5" title="Maroon 5">Maroon 5</a>
</td></tr>
<tr>
<td>9</td>
<td>"<a href="/wiki/The_Bones_(song)" title="The Bones (song)">The Bones</a>"</td>
<td><a href="/wiki/Maren_Morris" title="Maren Morris">Maren Morris</a>
</td></tr>
<tr>
<td>10</td>
<td>"<a href="/wiki/Someone_You_Loved" title="Someone You Loved">Someone You Loved</a>"</td>
<td><a href="/wiki/Lewis_Capaldi" title="Lewis Capaldi">Lewis Capaldi</a>
</td></tr>
<tr>
<td>11</td>
<td>"<a href="/wiki/Say_So" title="Say So">Say So</a>"</td>
<td><a href="/wiki/Doja_Cat" title="Doja Cat">Doja Cat</a>
</td></tr>
<tr>
<td>12</td>
<td>"<a href="/wiki/I_Hope_(Gabby_Barrett_song)" title="I Hope (Gabby Barrett song)">I Hope</a>"</td>
<td><a href="/wiki/Gabby_Barrett" title="Gabby Barrett">Gabby Barrett</a> featuring <a href="/wiki/Charlie_Puth" title="Charlie Puth">Charlie Puth</a>
</td></tr>
<tr>
<td>13</td>
<td>"<a href="/wiki/Whats_Poppin" title="Whats Poppin">Whats Poppin</a>"</td>
<td><a href="/wiki/Jack_Harlow" title="Jack Harlow">Jack Harlow</a> featuring <a href="/wiki/DaBaby" title="DaBaby">DaBaby</a>, <a href="/wiki/Tory_Lanez" title="Tory Lanez">Tory Lanez</a> and <a href="/wiki/Lil_Wayne" title="Lil Wayne">Lil Wayne</a>
</td></tr>
<tr>
<td>14</td>
<td>"<a href="/wiki/Dance_Monkey" title="Dance Monkey">Dance Monkey</a>"</td>
<td><a href="/wiki/Tones_and_I" title="Tones and I">Tones and I</a>
</td></tr>
<tr>
<td>15</td>
<td>"<a href="/wiki/Savage_(Megan_Thee_Stallion_song)" title="Savage (Megan Thee Stallion song)">Savage</a>"</td>
<td><a href="/wiki/Megan_Thee_Stallion" title="Megan Thee Stallion">Megan Thee Stallion</a> featuring <a href="/wiki/Beyonc%C3%A9" title="Beyoncé">Beyoncé</a>
</td></tr>
<tr>
<td>16</td>
<td>"<a href="/wiki/Roxanne_(Arizona_Zervas_song)" title="Roxanne (Arizona Zervas song)">Roxanne</a>"</td>
<td><a href="/wiki/Arizona_Zervas" title="Arizona Zervas">Arizona Zervas</a>
</td></tr>
<tr>
<td>17</td>
<td>"<a href="/wiki/Intentions_(Justin_Bieber_song)" title="Intentions (Justin Bieber song)">Intentions</a>"</td>
<td><a href="/wiki/Justin_Bieber" title="Justin Bieber">Justin Bieber</a> featuring <a href="/wiki/Quavo" title="Quavo">Quavo</a>
</td></tr>
<tr>
<td>18</td>
<td>"<a href="/wiki/Everything_I_Wanted" title="Everything I Wanted">Everything I Wanted</a>"</td>
<td><a href="/wiki/Billie_Eilish" title="Billie Eilish">Billie Eilish</a>
</td></tr>
<tr>
<td>19</td>
<td>"<a href="/wiki/Roses_(Saint_Jhn_song)" title="Roses (Saint Jhn song)">Roses (Imanbek remix)</a>"</td>
<td><a href="/wiki/Saint_Jhn" title="Saint Jhn">Saint Jhn</a>
</td></tr>
<tr>
<td>20</td>
<td>"<a href="/wiki/Watermelon_Sugar" title="Watermelon Sugar">Watermelon Sugar</a>"</td>
<td><a href="/wiki/Harry_Styles" title="Harry Styles">Harry Styles</a>
</td></tr>
<tr>
<td>21</td>
<td>"<a href="/wiki/Before_You_Go_(Lewis_Capaldi_song)" title="Before You Go (Lewis Capaldi song)">Before You Go</a>"</td>
<td><a href="/wiki/Lewis_Capaldi" title="Lewis Capaldi">Lewis Capaldi</a>
</td></tr>
<tr>
<td>22</td>
<td>"<a href="/wiki/Falling_(Trevor_Daniel_song)" title="Falling (Trevor Daniel song)">Falling</a>"</td>
<td><a href="/wiki/Trevor_Daniel_(singer)" title="Trevor Daniel (singer)">Trevor Daniel</a>
</td></tr>
<tr>
<td>23</td>
<td>"<a href="/wiki/10,000_Hours" title="10,000 Hours">10,000 Hours</a>"</td>
<td><a href="/wiki/Dan_%2B_Shay" title="Dan + Shay">Dan + Shay</a> and <a href="/wiki/Justin_Bieber" title="Justin Bieber">Justin Bieber</a>
</td></tr>
<tr>
<td>24</td>
<td>"<a href="/wiki/WAP_(song)" title="WAP (song)">WAP</a>"</td>
<td><a href="/wiki/Cardi_B" title="Cardi B">Cardi B</a> featuring <a href="/wiki/Megan_Thee_Stallion" title="Megan Thee Stallion">Megan Thee Stallion</a>
</td></tr>
<tr>
<td>25</td>
<td>"<a class="mw-redirect" href="/wiki/Ballin%27_(Mustard_song)" title="Ballin' (Mustard song)">Ballin'</a>"</td>
<td><a href="/wiki/Mustard_(record_producer)" title="Mustard (record producer)">Mustard</a> and <a href="/wiki/Roddy_Ricch" title="Roddy Ricch">Roddy Ricch</a>
</td></tr>
<tr>
<td>26</td>
<td>"<a href="/wiki/Hot_Girl_Bummer" title="Hot Girl Bummer">Hot Girl Bummer</a>"</td>
<td><a href="/wiki/Blackbear_(musician)" title="Blackbear (musician)">Blackbear</a>
</td></tr>
<tr>
<td>27</td>
<td>"<a href="/wiki/Blueberry_Faygo" title="Blueberry Faygo">Blueberry Faygo</a>"</td>
<td><a href="/wiki/Lil_Mosey" title="Lil Mosey">Lil Mosey</a>
</td></tr>
<tr>
<td>28</td>
<td>"<a href="/wiki/Heartless_(The_Weeknd_song)" title="Heartless (The Weeknd song)">Heartless</a>"</td>
<td><a href="/wiki/The_Weeknd" title="The Weeknd">The Weeknd</a>
</td></tr>
<tr>
<td>29</td>
<td>"<a href="/wiki/Bop_(DaBaby_song)" title="Bop (DaBaby song)">Bop</a>"</td>
<td><a href="/wiki/DaBaby" title="DaBaby">DaBaby</a>
</td></tr>
<tr>
<td>30</td>
<td>"<a href="/wiki/Lose_You_to_Love_Me" title="Lose You to Love Me">Lose You to Love Me</a>"</td>
<td><a href="/wiki/Selena_Gomez" title="Selena Gomez">Selena Gomez</a>
</td></tr>
<tr>
<td>31</td>
<td>"<a href="/wiki/Good_as_Hell" title="Good as Hell">Good as Hell</a>"</td>
<td><a href="/wiki/Lizzo" title="Lizzo">Lizzo</a>
</td></tr>
<tr>
<td>32</td>
<td>"<a href="/wiki/Toosie_Slide" title="Toosie Slide">Toosie Slide</a>"</td>
<td><a href="/wiki/Drake_(musician)" title="Drake (musician)">Drake</a>
</td></tr>
<tr>
<td>33</td>
<td>"<a href="/wiki/Break_My_Heart_(Dua_Lipa_song)" title="Break My Heart (Dua Lipa song)">Break My Heart</a>"</td>
<td><a href="/wiki/Dua_Lipa" title="Dua Lipa">Dua Lipa</a>
</td></tr>
<tr>
<td>34</td>
<td>"<a href="/wiki/Chasin%27_You" title="Chasin' You">Chasin' You</a>"</td>
<td><a href="/wiki/Morgan_Wallen" title="Morgan Wallen">Morgan Wallen</a>
</td></tr>
<tr>
<td>35</td>
<td>"<a href="/wiki/Savage_Love_(Laxed_%E2%80%93_Siren_Beat)" title="Savage Love (Laxed – Siren Beat)">Savage Love (Laxed – Siren Beat)</a>"</td>
<td><a href="/wiki/Jawsh_685" title="Jawsh 685">Jawsh 685</a> and <a href="/wiki/Jason_Derulo" title="Jason Derulo">Jason Derulo</a>
</td></tr>
<tr>
<td>36</td>
<td>"<a href="/wiki/No_Guidance" title="No Guidance">No Guidance</a>"</td>
<td><a href="/wiki/Chris_Brown" title="Chris Brown">Chris Brown</a> featuring <a href="/wiki/Drake_(musician)" title="Drake (musician)">Drake</a>
</td></tr>
<tr>
<td>37</td>
<td>"<a href="/wiki/My_Oh_My_(Camila_Cabello_song)" title="My Oh My (Camila Cabello song)">My Oh My</a>"</td>
<td><a href="/wiki/Camila_Cabello" title="Camila Cabello">Camila Cabello</a> featuring <a href="/wiki/DaBaby" title="DaBaby">DaBaby</a>
</td></tr>
<tr>
<td>38</td>
<td>"<a href="/wiki/Dynamite_(BTS_song)" title="Dynamite (BTS song)">Dynamite</a>"</td>
<td><a href="/wiki/BTS" title="BTS">BTS</a>
</td></tr>
<tr>
<td>39</td>
<td>"<a href="/wiki/Go_Crazy_(Chris_Brown_and_Young_Thug_song)" title="Go Crazy (Chris Brown and Young Thug song)">Go Crazy</a>"</td>
<td><a href="/wiki/Chris_Brown" title="Chris Brown">Chris Brown</a> and <a href="/wiki/Young_Thug" title="Young Thug">Young Thug</a>
</td></tr>
<tr>
<td>40</td>
<td>"<a href="/wiki/High_Fashion_(song)" title="High Fashion (song)">High Fashion</a>"</td>
<td><a href="/wiki/Roddy_Ricch" title="Roddy Ricch">Roddy Ricch</a> featuring <a href="/wiki/Mustard_(record_producer)" title="Mustard (record producer)">Mustard</a>
</td></tr>
<tr>
<td>41</td>
<td>"<a href="/wiki/Laugh_Now_Cry_Later" title="Laugh Now Cry Later">Laugh Now Cry Later</a>"</td>
<td><a href="/wiki/Drake_(musician)" title="Drake (musician)">Drake</a> featuring <a href="/wiki/Lil_Durk" title="Lil Durk">Lil Durk</a>
</td></tr>
<tr>
<td>42</td>
<td>"<a class="mw-redirect" href="/wiki/Woah_(Lil_Baby_song)" title="Woah (Lil Baby song)">Woah</a>"</td>
<td><a href="/wiki/Lil_Baby" title="Lil Baby">Lil Baby</a>
</td></tr>
<tr>
<td>43</td>
<td>"<a href="/wiki/Death_Bed_(Coffee_for_Your_Head)" title="Death Bed (Coffee for Your Head)">Death Bed</a>"</td>
<td><a href="/wiki/Powfu" title="Powfu">Powfu</a> featuring <a href="/wiki/Beabadoobee" title="Beabadoobee">Beabadoobee</a>
</td></tr>
<tr>
<td>44</td>
<td>"<a href="/wiki/Se%C3%B1orita_(Shawn_Mendes_and_Camila_Cabello_song)" title="Señorita (Shawn Mendes and Camila Cabello song)">Señorita</a>"</td>
<td><a href="/wiki/Shawn_Mendes" title="Shawn Mendes">Shawn Mendes</a> and <a href="/wiki/Camila_Cabello" title="Camila Cabello">Camila Cabello</a>
</td></tr>
<tr>
<td>45</td>
<td>"<a href="/wiki/Highest_in_the_Room" title="Highest in the Room">Highest in the Room</a>"</td>
<td><a href="/wiki/Travis_Scott" title="Travis Scott">Travis Scott</a>
</td></tr>
<tr>
<td>46</td>
<td>"<a href="/wiki/Bad_Guy_(Billie_Eilish_song)" title="Bad Guy (Billie Eilish song)">Bad Guy</a>"</td>
<td><a href="/wiki/Billie_Eilish" title="Billie Eilish">Billie Eilish</a>
</td></tr>
<tr>
<td>47</td>
<td>"<a href="/wiki/Mood_(24kGoldn_song)" title="Mood (24kGoldn song)">Mood</a>"</td>
<td><a href="/wiki/24kGoldn" title="24kGoldn">24kGoldn</a> featuring <a href="/wiki/Iann_Dior" title="Iann Dior">Iann Dior</a>
</td></tr>
<tr>
<td>48</td>
<td>"<a href="/wiki/Rain_on_Me_(Lady_Gaga_and_Ariana_Grande_song)" title="Rain on Me (Lady Gaga and Ariana Grande song)">Rain on Me</a>"</td>
<td><a href="/wiki/Lady_Gaga" title="Lady Gaga">Lady Gaga</a> and <a href="/wiki/Ariana_Grande" title="Ariana Grande">Ariana Grande</a>
</td></tr>
<tr>
<td>49</td>
<td>"<a href="/wiki/For_the_Night" title="For the Night">For the Night</a>"</td>
<td><a href="/wiki/Pop_Smoke" title="Pop Smoke">Pop Smoke</a> featuring <a href="/wiki/Lil_Baby" title="Lil Baby">Lil Baby</a> and <a href="/wiki/DaBaby" title="DaBaby">DaBaby</a>
</td></tr>
<tr>
<td>50</td>
<td>"<a class="mw-redirect" href="/wiki/Ritmo_(Bad_Boys_for_Life)" title="Ritmo (Bad Boys for Life)">Ritmo (Bad Boys for Life)</a>"</td>
<td><a href="/wiki/Black_Eyed_Peas" title="Black Eyed Peas">Black Eyed Peas</a> and <a href="/wiki/J_Balvin" title="J Balvin">J Balvin</a>
</td></tr>
<tr>
<td>51</td>
<td>"<a href="/wiki/Heart_on_Ice" title="Heart on Ice">Heart on Ice</a>"</td>
<td><a href="/wiki/Rod_Wave" title="Rod Wave">Rod Wave</a>
</td></tr>
<tr>
<td>52</td>
<td>"<a href="/wiki/Nobody_but_You_(Blake_Shelton_and_Gwen_Stefani_song)" title="Nobody but You (Blake Shelton and Gwen Stefani song)">Nobody but You</a>"</td>
<td><a href="/wiki/Blake_Shelton" title="Blake Shelton">Blake Shelton</a> and <a href="/wiki/Gwen_Stefani" title="Gwen Stefani">Gwen Stefani</a>
</td></tr>
<tr>
<td>53</td>
<td>"<a href="/wiki/Trampoline_(Shaed_song)" title="Trampoline (Shaed song)">Trampoline</a>"</td>
<td><a href="/wiki/Shaed" title="Shaed">Shaed</a>
</td></tr>
<tr>
<td>54</td>
<td>"<a class="mw-redirect" href="/wiki/Come_%26_Go_(Juice_Wrld_and_Marshmello_song)" title="Come &amp; Go (Juice Wrld and Marshmello song)">Come &amp; Go</a>"</td>
<td><a href="/wiki/Juice_Wrld" title="Juice Wrld">Juice Wrld</a> and <a href="/wiki/Marshmello" title="Marshmello">Marshmello</a>
</td></tr>
<tr>
<td>55</td>
<td>"<a href="/wiki/Truth_Hurts_(song)" title="Truth Hurts (song)">Truth Hurts</a>"</td>
<td><a href="/wiki/Lizzo" title="Lizzo">Lizzo</a>
</td></tr>
<tr>
<td>56</td>
<td>"<a href="/wiki/If_the_World_Was_Ending" title="If the World Was Ending">If the World Was Ending</a>"</td>
<td><a href="/wiki/JP_Saxe" title="JP Saxe">JP Saxe</a> featuring <a href="/wiki/Julia_Michaels" title="Julia Michaels">Julia Michaels</a>
</td></tr>
<tr>
<td>57</td>
<td>"<a href="/wiki/We_Paid" title="We Paid">We Paid</a>"</td>
<td><a href="/wiki/Lil_Baby" title="Lil Baby">Lil Baby</a> and <a href="/wiki/42_Dugg" title="42 Dugg">42 Dugg</a>
</td></tr>
<tr>
<td>58</td>
<td>"<a href="/wiki/Yummy_(Justin_Bieber_song)" title="Yummy (Justin Bieber song)">Yummy</a>"</td>
<td><a href="/wiki/Justin_Bieber" title="Justin Bieber">Justin Bieber</a>
</td></tr>
<tr>
<td>59</td>
<td>"<a href="/wiki/One_Man_Band_(Old_Dominion_song)" title="One Man Band (Old Dominion song)">One Man Band</a>"</td>
<td><a href="/wiki/Old_Dominion_(band)" title="Old Dominion (band)">Old Dominion</a>
</td></tr>
<tr>
<td>60</td>
<td>"<a href="/wiki/Got_What_I_Got" title="Got What I Got">Got What I Got</a>"</td>
<td><a href="/wiki/Jason_Aldean" title="Jason Aldean">Jason Aldean</a>
</td></tr>
<tr>
<td>61</td>
<td>"<a href="/wiki/Sunday_Best_(Surfaces_song)" title="Sunday Best (Surfaces song)">Sunday Best</a>"</td>
<td><a href="/wiki/Surfaces_(band)" title="Surfaces (band)">Surfaces</a>
</td></tr>
<tr>
<td>62</td>
<td>"<a class="mw-redirect" href="/wiki/Godzilla_(Eminem_song)" title="Godzilla (Eminem song)">Godzilla</a>"</td>
<td><a href="/wiki/Eminem" title="Eminem">Eminem</a> featuring <a href="/wiki/Juice_Wrld" title="Juice Wrld">Juice Wrld</a>
</td></tr>
<tr>
<td>63</td>
<td>"<a href="/wiki/Bandit_(Juice_Wrld_and_YoungBoy_Never_Broke_Again_song)" title="Bandit (Juice Wrld and YoungBoy Never Broke Again song)">Bandit</a>"</td>
<td><a href="/wiki/Juice_Wrld" title="Juice Wrld">Juice Wrld</a> and <a href="/wiki/YoungBoy_Never_Broke_Again" title="YoungBoy Never Broke Again">YoungBoy Never Broke Again</a>
</td></tr>
<tr>
<td>64</td>
<td>"<a href="/wiki/Party_Girl_(StaySolidRocky_song)" title="Party Girl (StaySolidRocky song)">Party Girl</a>"</td>
<td><a href="/wiki/StaySolidRocky" title="StaySolidRocky">StaySolidRocky</a>
</td></tr>
<tr>
<td>65</td>
<td>"<a href="/wiki/Die_from_a_Broken_Heart" title="Die from a Broken Heart">Die from a Broken Heart</a>"</td>
<td><a href="/wiki/Maddie_%26_Tae" title="Maddie &amp; Tae">Maddie &amp; Tae</a>
</td></tr>
<tr>
<td>66</td>
<td>"<a href="/wiki/Popstar_(DJ_Khaled_song)" title="Popstar (DJ Khaled song)">Popstar</a>"</td>
<td><a href="/wiki/DJ_Khaled" title="DJ Khaled">DJ Khaled</a> featuring <a href="/wiki/Drake_(musician)" title="Drake (musician)">Drake</a>
</td></tr>
<tr>
<td>67</td>
<td>"<a href="/wiki/All_I_Want_for_Christmas_Is_You" title="All I Want for Christmas Is You">All I Want for Christmas Is You</a>"</td>
<td><a href="/wiki/Mariah_Carey" title="Mariah Carey">Mariah Carey</a>
</td></tr>
<tr>
<td>68</td>
<td>"<a href="/wiki/One_of_Them_Girls" title="One of Them Girls">One of Them Girls</a>"</td>
<td><a href="/wiki/Lee_Brice" title="Lee Brice">Lee Brice</a>
</td></tr>
<tr>
<td>69</td>
<td>"<a href="/wiki/Hard_to_Forget" title="Hard to Forget">Hard to Forget</a>"</td>
<td><a href="/wiki/Sam_Hunt" title="Sam Hunt">Sam Hunt</a>
</td></tr>
<tr>
<td>70</td>
<td>"<a href="/wiki/One_Margarita" title="One Margarita">One Margarita</a>"</td>
<td><a href="/wiki/Luke_Bryan" title="Luke Bryan">Luke Bryan</a>
</td></tr>
<tr>
<td>71</td>
<td>"<a href="/wiki/Panini_(song)" title="Panini (song)">Panini</a>"</td>
<td><a href="/wiki/Lil_Nas_X" title="Lil Nas X">Lil Nas X</a>
</td></tr>
<tr>
<td>72</td>
<td>"<a href="/wiki/Hot_(Young_Thug_song)" title="Hot (Young Thug song)">Hot</a>"</td>
<td><a href="/wiki/Young_Thug" title="Young Thug">Young Thug</a> featuring <a href="/wiki/Gunna_(rapper)" title="Gunna (rapper)">Gunna</a>
</td></tr>
<tr>
<td>73</td>
<td>"<a href="/wiki/I_Hope_You%27re_Happy_Now_(Carly_Pearce_and_Lee_Brice_song)" title="I Hope You're Happy Now (Carly Pearce and Lee Brice song)">I Hope You're Happy Now</a>"</td>
<td><a href="/wiki/Carly_Pearce" title="Carly Pearce">Carly Pearce</a> and <a href="/wiki/Lee_Brice" title="Lee Brice">Lee Brice</a>
</td></tr>
<tr>
<td>74</td>
<td>"<a href="/wiki/Emotionally_Scarred" title="Emotionally Scarred">Emotionally Scarred</a>"</td>
<td><a href="/wiki/Lil_Baby" title="Lil Baby">Lil Baby</a>
</td></tr>
<tr>
<td>75</td>
<td>"<a href="/wiki/Suicidal_(song)" title="Suicidal (song)">Suicidal</a>"</td>
<td><a href="/wiki/YNW_Melly" title="YNW Melly">YNW Melly</a> featuring <a href="/wiki/Juice_Wrld" title="Juice Wrld">Juice Wrld</a>
</td></tr>
<tr>
<td>76</td>
<td>"<a href="/wiki/The_Bigger_Picture_(song)" title="The Bigger Picture (song)">The Bigger Picture</a>"</td>
<td><a href="/wiki/Lil_Baby" title="Lil Baby">Lil Baby</a>
</td></tr>
<tr>
<td>77</td>
<td>"<a href="/wiki/Only_Human_(Jonas_Brothers_song)" title="Only Human (Jonas Brothers song)">Only Human</a>"</td>
<td><a href="/wiki/Jonas_Brothers" title="Jonas Brothers">Jonas Brothers</a>
</td></tr>
<tr>
<td>78</td>
<td>"<a href="/wiki/The_Woo" title="The Woo">The Woo</a>"</td>
<td><a href="/wiki/Pop_Smoke" title="Pop Smoke">Pop Smoke</a> featuring <a href="/wiki/50_Cent" title="50 Cent">50 Cent</a> and <a href="/wiki/Roddy_Ricch" title="Roddy Ricch">Roddy Ricch</a>
</td></tr>
<tr>
<td>79</td>
<td>"<a href="/wiki/Sum_2_Prove" title="Sum 2 Prove">Sum 2 Prove</a>"</td>
<td><a href="/wiki/Lil_Baby" title="Lil Baby">Lil Baby</a>
</td></tr>
<tr>
<td>80</td>
<td>"<a href="/wiki/Stuck_with_U" title="Stuck with U">Stuck with U</a>"</td>
<td><a href="/wiki/Ariana_Grande" title="Ariana Grande">Ariana Grande</a> and <a href="/wiki/Justin_Bieber" title="Justin Bieber">Justin Bieber</a>
</td></tr>
<tr>
<td>81</td>
<td>"<a href="/wiki/Mood_Swings_(Pop_Smoke_song)" title="Mood Swings (Pop Smoke song)">Mood Swings</a>"</td>
<td><a href="/wiki/Pop_Smoke" title="Pop Smoke">Pop Smoke</a> featuring <a href="/wiki/Lil_Tjay" title="Lil Tjay">Lil Tjay</a>
</td></tr>
<tr>
<td>82</td>
<td>"<a href="/wiki/You_Should_Be_Sad" title="You Should Be Sad">You Should Be Sad</a>"</td>
<td><a href="/wiki/Halsey_(singer)" title="Halsey (singer)">Halsey</a>
</td></tr>
<tr>
<td>83</td>
<td>"<a href="/wiki/Dior_(song)" title="Dior (song)">Dior</a>"</td>
<td><a href="/wiki/Pop_Smoke" title="Pop Smoke">Pop Smoke</a>
</td></tr>
<tr>
<td>84</td>
<td>"<a href="/wiki/Supalonely" title="Supalonely">Supalonely</a>"</td>
<td><a href="/wiki/Benee" title="Benee">Benee</a> featuring <a href="/wiki/Gus_Dapperton" title="Gus Dapperton">Gus Dapperton</a>
</td></tr>
<tr>
<td>85</td>
<td>"<a href="/wiki/Even_Though_I%27m_Leaving" title="Even Though I'm Leaving">Even Though I'm Leaving</a>"</td>

In [148]:
table.find_all('th')
head = table.find_all('th')
head

[<th scope="col" style="background:#dde;"><abbr title="Number">No.</abbr>
 </th>,
 <th scope="col" style="background:#dde;">Title
 </th>,
 <th scope="col" style="background:#dde;">Artist(s)
 </th>]

In [149]:
[header.text.strip() for header in head]
header = [header.text.strip() for header in head]
header

['No.', 'Title', 'Artist(s)']

In [150]:
pd.DataFrame(columns=header)
df = pd.DataFrame(columns=header)
df

Empty DataFrame
Columns: [No., Title, Artist(s)]
Index: []

In [151]:
table.find_all('tr')
data = table.find_all('tr')
data

[<tr>
 <th scope="col" style="background:#dde;"><abbr title="Number">No.</abbr>
 </th>
 <th scope="col" style="background:#dde;">Title
 </th>
 <th scope="col" style="background:#dde;">Artist(s)
 </th></tr>,
 <tr>
 <td>1</td>
 <td>"<a href="/wiki/Blinding_Lights" title="Blinding Lights">Blinding Lights</a>"</td>
 <td><a href="/wiki/The_Weeknd" title="The Weeknd">The Weeknd</a>
 </td></tr>,
 <tr>
 <td>2</td>
 <td>"<a href="/wiki/Circles_(Post_Malone_song)" title="Circles (Post Malone song)">Circles</a>"</td>
 <td><a href="/wiki/Post_Malone" title="Post Malone">Post Malone</a>
 </td></tr>,
 <tr>
 <td>3</td>
 <td>"<a href="/wiki/The_Box_(Roddy_Ricch_song)" title="The Box (Roddy Ricch song)">The Box</a>"</td>
 <td><a href="/wiki/Roddy_Ricch" title="Roddy Ricch">Roddy Ricch</a>
 </td></tr>,
 <tr>
 <td>4</td>
 <td>"<a href="/wiki/Don%27t_Start_Now" title="Don't Start Now">Don't Start Now</a>"</td>
 <td><a href="/wiki/Dua_Lipa" title="Dua Lipa">Dua Lipa</a>
 </td></tr>,
 <tr>
 <td>5</td>
 <td>"<a href="/wiki/Rockstar_(DaBaby_song)" title="Rockstar (DaBaby song)">Rockstar</a>"</td>
 <td><a href="/wiki/DaBaby" title="DaBaby">DaBaby</a> featuring <a href="/wiki/Roddy_Ricch" title="Roddy Ricch">Roddy Ricch</a>
 </td></tr>,
 <tr>
 <td>6</td>
 <td>"<a href="/wiki/Adore_You_(Harry_Styles_song)" title="Adore You (Harry Styles song)">Adore You</a>"</td>
 <td><a href="/wiki/Harry_Styles" title="Harry Styles">Harry Styles</a>
 </td></tr>,
 <tr>
 <td>7</td>
 <td>"<a href="/wiki/Life_Is_Good_(song)" title="Life Is Good (song)">Life Is Good</a>"</td>
 <td><a href="/wiki/Future_(rapper)" title="Future (rapper)">Future</a> featuring <a href="/wiki/Drake_(musician)" title="Drake (musician)">Drake</a>
 </td></tr>,
 <tr>
 <td>8</td>
 <td>"<a href="/wiki/Memories_(Maroon_5_song)" title="Memories (Maroon 5 song)">Memories</a>"</td>
 <td><a href="/wiki/Maroon_5" title="Maroon 5">Maroon 5</a>
 </td></tr>,
 <tr>
 <td>9</td>
 <td>"<a href="/wiki/The_Bones_(song)" title="The Bones (song)">The Bones</a>"</td>
 <td><a href="/wiki/Maren_Morris" title="Maren Morris">Maren Morris</a>
 </td></tr>,
 <tr>
 <td>10</td>
 <td>"<a href="/wiki/Someone_You_Loved" title="Someone You Loved">Someone You Loved</a>"</td>
 <td><a href="/wiki/Lewis_Capaldi" title="Lewis Capaldi">Lewis Capaldi</a>
 </td></tr>,
 <tr>
 <td>11</td>
 <td>"<a href="/wiki/Say_So" title="Say So">Say So</a>"</td>
 <td><a href="/wiki/Doja_Cat" title="Doja Cat">Doja Cat</a>
 </td></tr>,
 <tr>
 <td>12</td>
 <td>"<a href="/wiki/I_Hope_(Gabby_Barrett_song)" title="I Hope (Gabby Barrett song)">I Hope</a>"</td>
 <td><a href="/wiki/Gabby_Barrett" title="Gabby Barrett">Gabby Barrett</a> featuring <a href="/wiki/Charlie_Puth" title="Charlie Puth">Charlie Puth</a>
 </td></tr>,
 <tr>
 <td>13</td>
 <td>"<a href="/wiki/Whats_Poppin" title="Whats Poppin">Whats Poppin</a>"</td>
 <td><a href="/wiki/Jack_Harlow" title="Jack Harlow">Jack Harlow</a> featuring <a href="/wiki/DaBaby" title="DaBaby">DaBaby</a>, <a href="/wiki/Tory_Lanez" title="Tory Lanez">Tory Lanez</a> and <a href="/wiki/Lil_Wayne" title="Lil Wayne">Lil Wayne</a>
 </td></tr>,
 <tr>
 <td>14</td>
 <td>"<a href="/wiki/Dance_Monkey" title="Dance Monkey">Dance Monkey</a>"</td>
 <td><a href="/wiki/Tones_and_I" title="Tones and I">Tones and I</a>
 </td></tr>,
 <tr>
 <td>15</td>
 <td>"<a href="/wiki/Savage_(Megan_Thee_Stallion_song)" title="Savage (Megan Thee Stallion song)">Savage</a>"</td>
 <td><a href="/wiki/Megan_Thee_Stallion" title="Megan Thee Stallion">Megan Thee Stallion</a> featuring <a href="/wiki/Beyonc%C3%A9" title="Beyoncé">Beyoncé</a>
 </td></tr>,
 <tr>
 <td>16</td>
 <td>"<a href="/wiki/Roxanne_(Arizona_Zervas_song)" title="Roxanne (Arizona Zervas song)">Roxanne</a>"</td>
 <td><a href="/wiki/Arizona_Zervas" title="Arizona Zervas">Arizona Zervas</a>
 </td></tr>,
 <tr>
 <td>17</td>
 <td>"<a href="/wiki/Intentions_(Justin_Bieber_song)" title="Intentions (Justin Bieber song)">Intentions</a>"</td>
 <td><a href="/wiki/Justin_Bieber" title="Justin Bieber">Justin Bieber</a> featuring <a href="/wiki/Quavo" title="Quavo">Quavo</a>
 </td></tr>,
 <tr>
 <td>18</td>
 <td>"<a href="/wiki/Everything_I_Wanted" title="Everything I Wanted">Everything I Wanted</a>"</td>
 <td><a href="/wiki/Billie_Eilish" title="Billie Eilish">Billie Eilish</a>
 </td></tr>,
 <tr>
 <td>19</td>
 <td>"<a href="/wiki/Roses_(Saint_Jhn_song)" title="Roses (Saint Jhn song)">Roses (Imanbek remix)</a>"</td>
 <td><a href="/wiki/Saint_Jhn" title="Saint Jhn">Saint Jhn</a>
 </td></tr>,
 <tr>
 <td>20</td>
 <td>"<a href="/wiki/Watermelon_Sugar" title="Watermelon Sugar">Watermelon Sugar</a>"</td>
 <td><a href="/wiki/Harry_Styles" title="Harry Styles">Harry Styles</a>
 </td></tr>,
 <tr>
 <td>21</td>
 <td>"<a href="/wiki/Before_You_Go_(Lewis_Capaldi_song)" title="Before You Go (Lewis Capaldi song)">Before You Go</a>"</td>
 <td><a href="/wiki/Lewis_Capaldi" title="Lewis Capaldi">Lewis Capaldi</a>
 </td></tr>,
 <tr>
 <td>22</td>
 <td>"<a href="/wiki/Falling_(Trevor_Daniel_song)" title="Falling (Trevor Daniel song)">Falling</a>"</td>
 <td><a href="/wiki/Trevor_Daniel_(singer)" title="Trevor Daniel (singer)">Trevor Daniel</a>
 </td></tr>,
 <tr>
 <td>23</td>
 <td>"<a href="/wiki/10,000_Hours" title="10,000 Hours">10,000 Hours</a>"</td>
 <td><a href="/wiki/Dan_%2B_Shay" title="Dan + Shay">Dan + Shay</a> and <a href="/wiki/Justin_Bieber" title="Justin Bieber">Justin Bieber</a>
 </td></tr>,
 <tr>
 <td>24</td>
 <td>"<a href="/wiki/WAP_(song)" title="WAP (song)">WAP</a>"</td>
 <td><a href="/wiki/Cardi_B" title="Cardi B">Cardi B</a> featuring <a href="/wiki/Megan_Thee_Stallion" title="Megan Thee Stallion">Megan Thee Stallion</a>
 </td></tr>,
 <tr>
 <td>25</td>
 <td>"<a class="mw-redirect" href="/wiki/Ballin%27_(Mustard_song)" title="Ballin' (Mustard song)">Ballin'</a>"</td>
 <td><a href="/wiki/Mustard_(record_producer)" title="Mustard (record producer)">Mustard</a> and <a href="/wiki/Roddy_Ricch" title="Roddy Ricch">Roddy Ricch</a>
 </td></tr>,
 <tr>
 <td>26</td>
 <td>"<a href="/wiki/Hot_Girl_Bummer" title="Hot Girl Bummer">Hot Girl Bummer</a>"</td>
 <td><a href="/wiki/Blackbear_(musician)" title="Blackbear (musician)">Blackbear</a>
 </td></tr>,
 <tr>
 <td>27</td>
 <td>"<a href="/wiki/Blueberry_Faygo" title="Blueberry Faygo">Blueberry Faygo</a>"</td>
 <td><a href="/wiki/Lil_Mosey" title="Lil Mosey">Lil Mosey</a>
 </td></tr>,
 <tr>
 <td>28</td>
 <td>"<a href="/wiki/Heartless_(The_Weeknd_song)" title="Heartless (The Weeknd song)">Heartless</a>"</td>
 <td><a href="/wiki/The_Weeknd" title="The Weeknd">The Weeknd</a>
 </td></tr>,
 <tr>
 <td>29</td>
 <td>"<a href="/wiki/Bop_(DaBaby_song)" title="Bop (DaBaby song)">Bop</a>"</td>
 <td><a href="/wiki/DaBaby" title="DaBaby">DaBaby</a>
 </td></tr>,
 <tr>
 <td>30</td>
 <td>"<a href="/wiki/Lose_You_to_Love_Me" title="Lose You to Love Me">Lose You to Love Me</a>"</td>
 <td><a href="/wiki/Selena_Gomez" title="Selena Gomez">Selena Gomez</a>
 </td></tr>,
 <tr>
 <td>31</td>
 <td>"<a href="/wiki/Good_as_Hell" title="Good as Hell">Good as Hell</a>"</td>
 <td><a href="/wiki/Lizzo" title="Lizzo">Lizzo</a>
 </td></tr>,
 <tr>
 <td>32</td>
 <td>"<a href="/wiki/Toosie_Slide" title="Toosie Slide">Toosie Slide</a>"</td>
 <td><a href="/wiki/Drake_(musician)" title="Drake (musician)">Drake</a>
 </td></tr>,
 <tr>
 <td>33</td>
 <td>"<a href="/wiki/Break_My_Heart_(Dua_Lipa_song)" title="Break My Heart (Dua Lipa song)">Break My Heart</a>"</td>
 <td><a href="/wiki/Dua_Lipa" title="Dua Lipa">Dua Lipa</a>
 </td></tr>,
 <tr>
 <td>34</td>
 <td>"<a href="/wiki/Chasin%27_You" title="Chasin' You">Chasin' You</a>"</td>
 <td><a href="/wiki/Morgan_Wallen" title="Morgan Wallen">Morgan Wallen</a>
 </td></tr>,
 <tr>
 <td>35</td>
 <td>"<a href="/wiki/Savage_Love_(Laxed_%E2%80%93_Siren_Beat)" title="Savage Love (Laxed – Siren Beat)">Savage Love (Laxed – Siren Beat)</a>"</td>
 <td><a href="/wiki/Jawsh_685" title="Jawsh 685">Jawsh 685</a> and <a href="/wiki/Jason_Derulo" title="Jason Derulo">Jason Derulo</a>
 </td></tr>,
 <tr>
 <td>36</td>
 <td>"<a href="/wiki/No_Guidance" title="No Guidance">No Guidance</a>"</td>
 <td><a href="/wiki/Chris_Brown" title="Chris Brown">Chris Brown</a> featuring <a href="/wiki/Drake_(musician)" title="Drake (musician)">Drake</a>
 </td></tr>,
 <tr>
 <td>37</td>
 <td>"<a href="/wiki/My_Oh_My_(Camila_Cabello_song)" title="My Oh My (Camila Cabello song)">My Oh My</a>"</td>
 <td><a href="/wiki/Camila_Cabello" title="Camila Cabello">Camila Cabello</a> featuring <a href="/wiki/DaBaby" title="DaBaby">DaBaby</a>
 </td></tr>,
 <tr>
 <td>38</td>
 <td>"<a href="/wiki/Dynamite_(BTS_song)" title="Dynamite (BTS song)">Dynamite</a>"</td>
 <td><a href="/wiki/BTS" title="BTS">BTS</a>
 </td></tr>,
 <tr>
 <td>39</td>
 <td>"<a href="/wiki/Go_Crazy_(Chris_Brown_and_Young_Thug_song)" title="Go Crazy (Chris Brown and Young Thug song)">Go Crazy</a>"</td>
 <td><a href="/wiki/Chris_Brown" title="Chris Brown">Chris Brown</a> and <a href="/wiki/Young_Thug" title="Young Thug">Young Thug</a>
 </td></tr>,
 <tr>
 <td>40</td>
 <td>"<a href="/wiki/High_Fashion_(song)" title="High Fashion (song)">High Fashion</a>"</td>
 <td><a href="/wiki/Roddy_Ricch" title="Roddy Ricch">Roddy Ricch</a> featuring <a href="/wiki/Mustard_(record_producer)" title="Mustard (record producer)">Mustard</a>
 </td></tr>,
 <tr>
 <td>41</td>
 <td>"<a href="/wiki/Laugh_Now_Cry_Later" title="Laugh Now Cry Later">Laugh Now Cry Later</a>"</td>
 <td><a href="/wiki/Drake_(musician)" title="Drake (musician)">Drake</a> featuring <a href="/wiki/Lil_Durk" title="Lil Durk">Lil Durk</a>
 </td></tr>,
 <tr>
 <td>42</td>
 <td>"<a class="mw-redirect" href="/wiki/Woah_(Lil_Baby_song)" title="Woah (Lil Baby song)">Woah</a>"</td>
 <td><a href="/wiki/Lil_Baby" title="Lil Baby">Lil Baby</a>
 </td></tr>,
 <tr>
 <td>43</td>
 <td>"<a href="/wiki/Death_Bed_(Coffee_for_Your_Head)" title="Death Bed (Coffee for Your Head)">Death Bed</a>"</td>
 <td><a href="/wiki/Powfu" title="Powfu">Powfu</a> featuring <a href="/wiki/Beabadoobee" title="Beabadoobee">Beabadoobee</a>
 </td></tr>,
 <tr>
 <td>44</td>
 <td>"<a href="/wiki/Se%C3%B1orita_(Shawn_Mendes_and_Camila_Cabello_song)" title="Señorita (Shawn Mendes and Camila Cabello song)">Señorita</a>"</td>
 <td><a href="/wiki/Shawn_Mendes" title="Shawn Mendes">Shawn Mendes</a> and <a href="/wiki/Camila_Cabello" title="Camila Cabello">Camila Cabello</a>
 </td></tr>,
 <tr>
 <td>45</td>
 <td>"<a href="/wiki/Highest_in_the_Room" title="Highest in the Room">Highest in the Room</a>"</td>
 <td><a href="/wiki/Travis_Scott" title="Travis Scott">Travis Scott</a>
 </td></tr>,
 <tr>
 <td>46</td>
 <td>"<a href="/wiki/Bad_Guy_(Billie_Eilish_song)" title="Bad Guy (Billie Eilish song)">Bad Guy</a>"</td>
 <td><a href="/wiki/Billie_Eilish" title="Billie Eilish">Billie Eilish</a>
 </td></tr>,
 <tr>
 <td>47</td>
 <td>"<a href="/wiki/Mood_(24kGoldn_song)" title="Mood (24kGoldn song)">Mood</a>"</td>
 <td><a href="/wiki/24kGoldn" title="24kGoldn">24kGoldn</a> featuring <a href="/wiki/Iann_Dior" title="Iann Dior">Iann Dior</a>
 </td></tr>,
 <tr>
 <td>48</td>
 <td>"<a href="/wiki/Rain_on_Me_(Lady_Gaga_and_Ariana_Grande_song)" title="Rain on Me (Lady Gaga and Ariana Grande song)">Rain on Me</a>"</td>
 <td><a href="/wiki/Lady_Gaga" title="Lady Gaga">Lady Gaga</a> and <a href="/wiki/Ariana_Grande" title="Ariana Grande">Ariana Grande</a>
 </td></tr>,
 <tr>
 <td>49</td>
 <td>"<a href="/wiki/For_the_Night" title="For the Night">For the Night</a>"</td>
 <td><a href="/wiki/Pop_Smoke" title="Pop Smoke">Pop Smoke</a> featuring <a href="/wiki/Lil_Baby" title="Lil Baby">Lil Baby</a> and <a href="/wiki/DaBaby" title="DaBaby">DaBaby</a>
 </td></tr>,
 <tr>
 <td>50</td>
 <td>"<a class="mw-redirect" href="/wiki/Ritmo_(Bad_Boys_for_Life)" title="Ritmo (Bad Boys for Life)">Ritmo (Bad Boys for Life)</a>"</td>
 <td><a href="/wiki/Black_Eyed_Peas" title="Black Eyed Peas">Black Eyed Peas</a> and <a href="/wiki/J_Balvin" title="J Balvin">J Balvin</a>
 </td></tr>,
 <tr>
 <td>51</td>
 <td>"<a href="/wiki/Heart_on_Ice" title="Heart on Ice">Heart on Ice</a>"</td>
 <td><a href="/wiki/Rod_Wave" title="Rod Wave">Rod Wave</a>
 </td></tr>,
 <tr>
 <td>52</td>
 <td>"<a href="/wiki/Nobody_but_You_(Blake_Shelton_and_Gwen_Stefani_song)" title="Nobody but You (Blake Shelton and Gwen Stefani song)">Nobody but You</a>"</td>
 <td><a href="/wiki/Blake_Shelton" title="Blake Shelton">Blake Shelton</a> and <a href="/wiki/Gwen_Stefani" title="Gwen Stefani">Gwen Stefani</a>
 </td></tr>,
 <tr>
 <td>53</td>
 <td>"<a href="/wiki/Trampoline_(Shaed_song)" title="Trampoline (Shaed song)">Trampoline</a>"</td>
 <td><a href="/wiki/Shaed" title="Shaed">Shaed</a>
 </td></tr>,
 <tr>
 <td>54</td>
 <td>"<a class="mw-redirect" href="/wiki/Come_%26_Go_(Juice_Wrld_and_Marshmello_song)" title="Come &amp; Go (Juice Wrld and Marshmello song)">Come &amp; Go</a>"</td>
 <td><a href="/wiki/Juice_Wrld" title="Juice Wrld">Juice Wrld</a> and <a href="/wiki/Marshmello" title="Marshmello">Marshmello</a>
 </td></tr>,
 <tr>
 <td>55</td>
 <td>"<a href="/wiki/Truth_Hurts_(song)" title="Truth Hurts (song)">Truth Hurts</a>"</td>
 <td><a href="/wiki/Lizzo" title="Lizzo">Lizzo</a>
 </td></tr>,
 <tr>
 <td>56</td>
 <td>"<a href="/wiki/If_the_World_Was_Ending" title="If the World Was Ending">If the World Was Ending</a>"</td>
 <td><a href="/wiki/JP_Saxe" title="JP Saxe">JP Saxe</a> featuring <a href="/wiki/Julia_Michaels" title="Julia Michaels">Julia Michaels</a>
 </td></tr>,
 <tr>
 <td>57</td>
 <td>"<a href="/wiki/We_Paid" title="We Paid">We Paid</a>"</td>
 <td><a href="/wiki/Lil_Baby" title="Lil Baby">Lil Baby</a> and <a href="/wiki/42_Dugg" title="42 Dugg">42 Dugg</a>
 </td></tr>,
 <tr>
 <td>58</td>
 <td>"<a href="/wiki/Yummy_(Justin_Bieber_song)" title="Yummy (Justin Bieber song)">Yummy</a>"</td>
 <td><a href="/wiki/Justin_Bieber" title="Justin Bieber">Justin Bieber</a>
 </td></tr>,
 <tr>
 <td>59</td>
 <td>"<a href="/wiki/One_Man_Band_(Old_Dominion_song)" title="One Man Band (Old Dominion song)">One Man Band</a>"</td>
 <td><a href="/wiki/Old_Dominion_(band)" title="Old Dominion (band)">Old Dominion</a>
 </td></tr>,
 <tr>
 <td>60</td>
 <td>"<a href="/wiki/Got_What_I_Got" title="Got What I Got">Got What I Got</a>"</td>
 <td><a href="/wiki/Jason_Aldean" title="Jason Aldean">Jason Aldean</a>
 </td></tr>,
 <tr>
 <td>61</td>
 <td>"<a href="/wiki/Sunday_Best_(Surfaces_song)" title="Sunday Best (Surfaces song)">Sunday Best</a>"</td>
 <td><a href="/wiki/Surfaces_(band)" title="Surfaces (band)">Surfaces</a>
 </td></tr>,
 <tr>
 <td>62</td>
 <td>"<a class="mw-redirect" href="/wiki/Godzilla_(Eminem_song)" title="Godzilla (Eminem song)">Godzilla</a>"</td>
 <td><a href="/wiki/Eminem" title="Eminem">Eminem</a> featuring <a href="/wiki/Juice_Wrld" title="Juice Wrld">Juice Wrld</a>
 </td></tr>,
 <tr>
 <td>63</td>
 <td>"<a href="/wiki/Bandit_(Juice_Wrld_and_YoungBoy_Never_Broke_Again_song)" title="Bandit (Juice Wrld and YoungBoy Never Broke Again song)">Bandit</a>"</td>
 <td><a href="/wiki/Juice_Wrld" title="Juice Wrld">Juice Wrld</a> and <a href="/wiki/YoungBoy_Never_Broke_Again" title="YoungBoy Never Broke Again">YoungBoy Never Broke Again</a>
 </td></tr>,
 <tr>
 <td>64</td>
 <td>"<a href="/wiki/Party_Girl_(StaySolidRocky_song)" title="Party Girl (StaySolidRocky song)">Party Girl</a>"</td>
 <td><a href="/wiki/StaySolidRocky" title="StaySolidRocky">StaySolidRocky</a>
 </td></tr>,
 <tr>
 <td>65</td>
 <td>"<a href="/wiki/Die_from_a_Broken_Heart" title="Die from a Broken Heart">Die from a Broken Heart</a>"</td>
 <td><a href="/wiki/Maddie_%26_Tae" title="Maddie &amp; Tae">Maddie &amp; Tae</a>
 </td></tr>,
 <tr>
 <td>66</td>
 <td>"<a href="/wiki/Popstar_(DJ_Khaled_song)" title="Popstar (DJ Khaled song)">Popstar</a>"</td>
 <td><a href="/wiki/DJ_Khaled" title="DJ Khaled">DJ Khaled</a> featuring <a href="/wiki/Drake_(musician)" title="Drake (musician)">Drake</a>
 </td></tr>,
 <tr>
 <td>67</td>
 <td>"<a href="/wiki/All_I_Want_for_Christmas_Is_You" title="All I Want for Christmas Is You">All I Want for Christmas Is You</a>"</td>
 <td><a href="/wiki/Mariah_Carey" title="Mariah Carey">Mariah Carey</a>
 </td></tr>,
 <tr>
 <td>68</td>
 <td>"<a href="/wiki/One_of_Them_Girls" title="One of Them Girls">One of Them Girls</a>"</td>
 <td><a href="/wiki/Lee_Brice" title="Lee Brice">Lee Brice</a>
 </td></tr>,
 <tr>
 <td>69</td>
 <td>"<a href="/wiki/Hard_to_Forget" title="Hard to Forget">Hard to Forget</a>"</td>
 <td><a href="/wiki/Sam_Hunt" title="Sam Hunt">Sam Hunt</a>
 </td></tr>,
 <tr>
 <td>70</td>
 <td>"<a href="/wiki/One_Margarita" title="One Margarita">One Margarita</a>"</td>
 <td><a href="/wiki/Luke_Bryan" title="Luke Bryan">Luke Bryan</a>
 </td></tr>,
 <tr>
 <td>71</td>
 <td>"<a href="/wiki/Panini_(song)" title="Panini (song)">Panini</a>"</td>
 <td><a href="/wiki/Lil_Nas_X" title="Lil Nas X">Lil Nas X</a>
 </td></tr>,
 <tr>
 <td>72</td>
 <td>"<a href="/wiki/Hot_(Young_Thug_song)" title="Hot (Young Thug song)">Hot</a>"</td>
 <td><a href="/wiki/Young_Thug" title="Young Thug">Young Thug</a> featuring <a href="/wiki/Gunna_(rapper)" title="Gunna (rapper)">Gunna</a>
 </td></tr>,
 <tr>
 <td>73</td>
 <td>"<a href="/wiki/I_Hope_You%27re_Happy_Now_(Carly_Pearce_and_Lee_Brice_song)" title="I Hope You're Happy Now (Carly Pearce and Lee Brice song)">I Hope You're Happy Now</a>"</td>
 <td><a href="/wiki/Carly_Pearce" title="Carly Pearce">Carly Pearce</a> and <a href="/wiki/Lee_Brice" title="Lee Brice">Lee Brice</a>
 </td></tr>,
 <tr>
 <td>74</td>
 <td>"<a href="/wiki/Emotionally_Scarred" title="Emotionally Scarred">Emotionally Scarred</a>"</td>
 <td><a href="/wiki/Lil_Baby" title="Lil Baby">Lil Baby</a>
 </td></tr>,
 <tr>
 <td>75</td>
 <td>"<a href="/wiki/Suicidal_(song)" title="Suicidal (song)">Suicidal</a>"</td>
 <td><a href="/wiki/YNW_Melly" title="YNW Melly">YNW Melly</a> featuring <a href="/wiki/Juice_Wrld" title="Juice Wrld">Juice Wrld</a>
 </td></tr>,
 <tr>
 <td>76</td>
 <td>"<a href="/wiki/The_Bigger_Picture_(song)" title="The Bigger Picture (song)">The Bigger Picture</a>"</td>
 <td><a href="/wiki/Lil_Baby" title="Lil Baby">Lil Baby</a>
 </td></tr>,
 <tr>
 <td>77</td>
 <td>"<a href="/wiki/Only_Human_(Jonas_Brothers_song)" title="Only Human (Jonas Brothers song)">Only Human</a>"</td>
 <td><a href="/wiki/Jonas_Brothers" title="Jonas Brothers">Jonas Brothers</a>
 </td></tr>,
 <tr>
 <td>78</td>
 <td>"<a href="/wiki/The_Woo" title="The Woo">The Woo</a>"</td>
 <td><a href="/wiki/Pop_Smoke" title="Pop Smoke">Pop Smoke</a> featuring <a href="/wiki/50_Cent" title="50 Cent">50 Cent</a> and <a href="/wiki/Roddy_Ricch" title="Roddy Ricch">Roddy Ricch</a>
 </td></tr>,
 <tr>
 <td>79</td>
 <td>"<a href="/wiki/Sum_2_Prove" title="Sum 2 Prove">Sum 2 Prove</a>"</td>
 <td><a href="/wiki/Lil_Baby" title="Lil Baby">Lil Baby</a>
 </td></tr>,
 <tr>
 <td>80</td>
 <td>"<a href="/wiki/Stuck_with_U" title="Stuck with U">Stuck with U</a>"</td>
 <td><a href="/wiki/Ariana_Grande" title="Ariana Grande">Ariana Grande</a> and <a href="/wiki/Justin_Bieber" title="Justin Bieber">Justin Bieber</a>
 </td></tr>,
 <tr>
 <td>81</td>
 <td>"<a href="/wiki/Mood_Swings_(Pop_Smoke_song)" title="Mood Swings (Pop Smoke song)">Mood Swings</a>"</td>
 <td><a href="/wiki/Pop_Smoke" title="Pop Smoke">Pop Smoke</a> featuring <a href="/wiki/Lil_Tjay" title="Lil Tjay">Lil Tjay</a>
 </td></tr>,
 <tr>
 <td>82</td>
 <td>"<a href="/wiki/You_Should_Be_Sad" title="You Should Be Sad">You Should Be Sad</a>"</td>
 <td><a href="/wiki/Halsey_(singer)" title="Halsey (singer)">Halsey</a>
 </td></tr>,
 <tr>
 <td>83</td>
 <td>"<a href="/wiki/Dior_(song)" title="Dior (song)">Dior</a>"</td>
 <td><a href="/wiki/Pop_Smoke" title="Pop Smoke">Pop Smoke</a>
 </td></tr>,
 <tr>
 <td>84</td>
 <td>"<a href="/wiki/Supalonely" title="Supalonely">Supalonely</a>"</td>
 <td><a href="/wiki/Benee" title="Benee">Benee</a> featuring <a href="/wiki/Gus_Dapperton" title="Gus Dapperton">Gus Dapperton</a>
 </td></tr>,
 <tr>
 <td>85</td>
 <td>"<a href="/wiki/Even_Though_I%27m_Leaving" title="Even Though I'm Leaving">Even Though I'm Leaving</a>"</td>

In [152]:
#To avoid "row with mismatched columns" we are using the index number on the for loop to remove the empty []
for rows in data[1:]:
    Rows = rows.find_all('td')
    DATA = [Data.text.strip() for Data in Rows]
    length =  len(df)
    df.loc[length] = DATA
df

,No.,Title,Artist(s)
0,1,"""Blinding Lights""",The Weeknd
1,2,"""Circles""",Post Malone
2,3,"""The Box""",Roddy Ricch
3,4,"""Don't Start Now""",Dua Lipa
4,5,"""Rockstar""",DaBaby featuring Roddy Ricch
5,6,"""Adore You""",Harry Styles
6,7,"""Life Is Good""",Future featuring Drake
7,8,"""Memories""",Maroon 5
8,9,"""The Bones""",Maren Morris
9,10,"""Someone You Loved""",Lewis Capaldi
10,11,"""Say So""",Doja Cat
11,12,"""I Hope""",Gabby Barrett featuring Charlie Puth
12,13,"""Whats Poppin""","Jack Harlow featuring DaBaby, Tory Lanez and L..."
13,14,"""Dance Monkey""",Tones and I
14,15,"""Savage""",Megan Thee Stallion featuring Beyoncé
15,16,"""Roxanne""",Arizona Zervas
16,17,"""Intentions""",Justin Bieber featuring Quavo
17,18,"""Everything I Wanted""",Billie Eilish
18,19,"""Roses (Imanbek remix)""",Saint Jhn
19,20,"""Watermelon Sugar""",Harry Styles
20,21,"""Before You Go""",Lewis Capaldi
21,22,"""Falling""",Trevor Daniel
22,23,"""10,000 Hours""",Dan + Shay and Justin Bieber
23,24,"""WAP""",Cardi B featuring Megan Thee Stallion
24,25,"""Ballin'""",Mustard and Roddy Ricch
25,26,"""Hot Girl Bummer""",Blackbear
26,27,"""Blueberry Faygo""",Lil Mosey
27,28,"""Heartless""",The Weeknd
28,29,"""Bop""",DaBaby
29,30,"""Lose You to Love Me""",Selena Gomez
30,31,"""Good as Hell""",Lizzo
31,32,"""Toosie Slide""",Drake
32,33,"""Break My Heart""",Dua Lipa
33,34,"""Chasin' You""",Morgan Wallen
34,35,"""Savage Love (Laxed – Siren Beat)""",Jawsh 685 and Jason Derulo
35,36,"""No Guidance""",Chris Brown featuring Drake
36,37,"""My Oh My""",Camila Cabello featuring DaBaby
37,38,"""Dynamite""",BTS
38,39,"""Go Crazy""",Chris Brown and Young Thug
39,40,"""High Fashion""",Roddy Ricch featuring Mustard
40,41,"""Laugh Now Cry Later""",Drake featuring Lil Durk
41,42,"""Woah""",Lil Baby
42,43,"""Death Bed""",Powfu featuring Beabadoobee
43,44,"""Señorita""",Shawn Mendes and Camila Cabello
44,45,"""Highest in the Room""",Travis Scott
45,46,"""Bad Guy""",Billie Eilish
46,47,"""Mood""",24kGoldn featuring Iann Dior
47,48,"""Rain on Me""",Lady Gaga and Ariana Grande
48,49,"""For the Night""",Pop Smoke featuring Lil Baby and DaBaby
49,50,"""Ritmo (Bad Boys for Life)""",Black Eyed Peas and J Balvin
50,51,"""Heart on Ice""",Rod Wave
51,52,"""Nobody but You""",Blake Shelton and Gwen Stefani
52,53,"""Trampoline""",Shaed
53,54,"""Come & Go""",Juice Wrld and Marshmello
54,55,"""Truth Hurts""",Lizzo
55,56,"""If the World Was Ending""",JP Saxe featuring Julia Michaels
56,57,"""We Paid""",Lil Baby and 42 Dugg
57,58,"""Yummy""",Justin Bieber
58,59,"""One Man Band""",Old Dominion
59,60,"""Got What I Got""",Jason Aldean
60,61,"""Sunday Best""",Surfaces
61,62,"""Godzilla""",Eminem featuring Juice Wrld
62,63,"""Bandit""",Juice Wrld and YoungBoy Never Broke Again
63,64,"""Party Girl""",StaySolidRocky
64,65,"""Die from a Broken Heart""",Maddie & Tae
65,66,"""Popstar""",DJ Khaled featuring Drake
66,67,"""All I Want for Christmas Is You""",Mariah Carey
67,68,"""One of Them Girls""",Lee Brice
68,69,"""Hard to Forget""",Sam Hunt
69,70,"""One Margarita""",Luke Bryan
70,71,"""Panini""",Lil Nas X
71,72,"""Hot""",Young Thug featuring Gunna
72,73,"""I Hope You're Happy Now""",Carly Pearce and Lee Brice
73,74,"""Emotionally Scarred""",Lil Baby
74,75,"""Suicidal""",YNW Melly featuring Juice Wrld
75,76,"""The Bigger Picture""",Lil Baby
76,77,"""Only Human""",Jonas Brothers
77,78,"""The Woo""",Pop Smoke featuring 50 Cent and Roddy Ricch
78,79,"""Sum 2 Prove""",Lil Baby
79,80,"""Stuck with U""",Ariana Grande and Justin Bieber
80,81,"""Mood Swings""",Pop Smoke featuring Lil Tjay
81,82,"""You Should Be Sad""",Halsey
82,83,"""Dior""",Pop Smoke
83,84,"""Supalonely""",Benee featuring Gus Dapperton
84,85,"""Even Though I'm Leaving""",Luke Combs
85,86,"""The Scotts""",The Scotts (Travis Scott and Kid Cudi)
86,87,"""Juicy""",Doja Cat and Tyga
87,88,"""Be Like That""","Kane Brown, Swae Lee and Khalid"
88,89,"""Homesick""",Kane Brown
89,90,"""Rags2Riches""",Rod Wave featuring ATR Son Son
90,91,"""Bluebird""",Miranda Lambert
91,92,"""Wishing Well""",Juice Wrld
92,93,"""Does to Me""",Luke Combs featuring Eric Church
93,94,"""Pussy Fairy (OTW)""",Jhené Aiko
94,95,"""ILY (I Love You Baby)""",Surf Mesa featuring Emilee
95,96,"""More Than My Hometown""",Morgan Wallen
96,97,"""Lovin' on You""",Luke Combs
97,98,"""Said Sum""",Moneybagg Yo
98,99,"""Slide""",H.E.R. featuring YG
99,100,"""Walk Em Down""",NLE Choppa featuring Roddy Ricch

In [154]:
df.to_csv(r'C:\Users\Reuben Yohanna Vandi\Pictures\python\List of songs on Billboards 2020 Year-End Hot 100 chart.csv', index = False)