In [1]:
from bs4 import BeautifulSoup
import requests

In [3]:
url = 'https://en.wikipedia.org/wiki/List_of_most_valuable_crops_and_livestock_products'

In [4]:
requests.get(url)

In [5]:
web = requests.get(url)

In [6]:
soup = BeautifulSoup(web.text, 'html')

In [7]:
print(soup)

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-sticky-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-toc-available" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>List of most valuable crops and livestock products - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-sticky-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-toc-available";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy",
"wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"83374031-b40f-475f-9d87-f3f98f063715","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_most_valuable_crops_and_livestock_products","wgTitle":"List of most valuable crops and livestock products","wgCurRevisionId":1241237024,"wgRevisionId":1241237024,"wgArticleId":40243509,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Agricultural production","Agriculture-related lists","Agricultural production by commodity","Economy-related lists of superlatives"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_most_valuable_crops_and_livestock_products","wgRelevantArticleId":40243509,
"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgCiteReferencePreviewsActive":false,"wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":6000,"wgRelatedArticlesCompat":[],"wgCentralAuthMobileDomain":false,"wgEditSubmitButtonLabelPublish":true,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q17098621","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],
"GEHomepageSuggestedEditsEnableTopics":true,"wgGETopicsMatchModeEnabled":false,"wgGEStructuredTaskRejectionReasonTextInputEnabled":false,"wgGELevelingUpEnabledForUser":false};RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","jquery.makeCollapsible.styles":"ready","ext.wikimediamessages.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready","ext.wikimediaBadges":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","mediawiki.page.media","ext.scribunto.logs","site","mediawiki.page.ready","jquery.tablesorter","jquery.makeCollapsible","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips",
"ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.visualEditor.targetLoader","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","ext.checkUser.clientHints","ext.growthExperiments.SuggestedEditSession","wikibase.sidebar.tracking"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cext.wikimediamessages.styles%7Cjquery.makeCollapsible.styles%7Cjquery.tablesorter.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<meta content="MediaWiki 1.44.0-wmf.4" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Rice_02.jpg/1200px-Rice_02.jpg" property="og:image"/>
<meta content="1200" property="og:image:width"/>
<meta content="770" property="og:image:height"/>
<meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Rice_02.jpg/800px-Rice_02.jpg" property="og:image"/>
<meta content="800" property="og:image:width"/>
<meta content="513" property="og:image:height"/>
<meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Rice_02.jpg/640px-Rice_02.jpg" property="og:image"/>
<meta content="640" property="og:image:width"/>
<meta content="411" property="og:image:height"/>
<meta content="width=1120" name="viewport"/>
<meta content="List of most valuable crops and livestock products - Wikipedia" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="//upload.wikimedia.org" rel="preconnect"/>
<link href="//en.m.wikipedia.org/wiki/List_of_most_valuable_crops_and_livestock_products" media="only screen and (max-width: 640px)" rel="alternate"/>
<link href="/w/index.php?title=List_of_most_valuable_crops_and_livestock_products&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
<link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://en.wikipedia.org/wiki/List_of_most_valuable_crops_and_livestock_products" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
<link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch"/>
<link href="//login.wikimedia.org" rel="dns-prefetch"/>
</head>
<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-List_of_most_valuable_crops_and_livestock_products rootpage-List_of_most_valuable_crops_and_livestock_products skin-vector-2022 action-view"><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
<header class="vector-header mw-header">
<div class="vector-header-start">
<nav aria-label="Site" class="vector-main-menu-landmark">
<div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown">
<input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>
<span class="vector-dropdown-label-text">Main menu</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Main menu</div>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navigation
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a></li><li class="mw-list-item" id="n-contents"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a></li><li class="mw-list-item" id="n-aboutsite"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li class="mw-list-item" id="n-contactpage"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
<div class="vector-menu-heading">
		Contribute
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-help"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li class="mw-list-item" id="n-introduction"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a></li><li class="mw-list-item" id="n-upload"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Main_Page">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/wikipedia.png" width="50"/>
<span class="mw-logo-container skin-invert">
<img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en.svg" style="width: 7.5em; height: 1.125em;"/>
<img alt="The Free Encyclopedia" class="mw-logo-tagline" height="13" src="/static/images/mobile/copyright/wikipedia-tagline-en.svg" style="width: 7.3125em; height: 0.8125em;" width="117"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>
<span>Search</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Search Wikipedia" autocapitalize="sentences" class="cdx-text-input__input" id="searchInput" name="search" placeholder="Search Wikipedia" title="Search Wikipedia [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Special:Search"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Search</button>
</form>
</div>
</div>
</div>
<nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
<div class="vector-user-links-main">
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<nav aria-label="Appearance" class="vector-appearance-landmark">
<div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
<input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label"><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance"></span>
<span class="vector-dropdown-label-text">Appearance</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
</div>
</div>
</div>
</nav>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-sitesupport-2"><a class="" data-mw="interface" href="https://donate.wikimedia.org/wiki/Special:FundraiserRedirector?utm_source=donate&amp;utm_medium=sidebar&amp;utm_campaign=C13_en.wikipedia.org&amp;uselang=en"><span>Donate</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-createaccount-2"><a class="" data-mw="interface" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+most+valuable+crops+and+livestock+products" title="You are encouraged to create an account and log in; however, it is not mandatory"><span>Create account</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-login-2"><a accesskey="o" class="" data-mw="interface" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+most+valuable+crops+and+livestock+products" title="You're encouraged to log in; however, it's not mandatory. [o]"><span>Log in</span></a>
</li>
</ul>
</div>
</div>
</div>
<div class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out" id="vector-user-links-dropdown" title="Log in and more options">
<input aria-haspopup="true" aria-label="Personal tools" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-user-links-dropdown" id="vector-user-links-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-user-links-dropdown-checkbox" id="vector-user-links-dropdown-label"><span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>
<span class="vector-dropdown-label-text">Personal tools</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item" id="p-personal" title="User menu">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item" id="pt-sitesupport"><a href="https://donate.wikimedia.org/wiki/Special:FundraiserRedirector?utm_source=donate&amp;utm_medium=sidebar&amp;utm_campaign=C13_en.wikipedia.org&amp;uselang=en"><span>Donate</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-createaccount"><a href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+most+valuable+crops+and+livestock+products" title="You are encouraged to create an account and log in; however, it is not mandatory"><span class="vector-icon mw-ui-icon-userAdd mw-ui-icon-wikimedia-userAdd"></span> <span>Create account</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-login"><a accesskey="o" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+most+valuable+crops+and+livestock+products" title="You're encouraged to log in; however, it's not mandatory. [o]"><span class="vector-icon mw-ui-icon-logIn mw-ui-icon-wikimedia-logIn"></span> <span>Log in</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-user-menu-anon-editor" id="p-user-menu-anon-editor">
<div class="vector-menu-heading">
		Pages for logged out editors <a aria-label="Learn more about editing" href="/wiki/Help:Introduction"><span>learn more</span></a>
</div>
<div class="vector-menu-content">

In [9]:
table = soup.find('table')
print(table)

<table class="wikitable sortable" style="text-align:center;">
<tbody><tr>
<th>Crop or Livestock</th>
<th>Global gross production value in billion US$</th>
<th data-sort-type="number">Global production in metric tons
</th>
<th>Global production in US$/metric ton</th>
<th>Country with highest gross production value in billion USD
</th></tr>
<tr>
<td><a href="/wiki/Rice" title="Rice">Rice</a>, paddy</td>
<td>$332</td>
<td>751,885,117
</td>
<td>$442</td>
<td>$117 (Mainland <a href="/wiki/China" title="China">China</a>)
</td></tr>
<tr>
<td><a class="mw-redirect" href="/wiki/Domestic_pig" title="Domestic pig">Pig</a>, meat</td>
<td>$280</td>
<td>118,956,327
</td>
<td>$2,354</td>
<td>$167 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Cattle" title="Cattle">Cattle</a>, meat</td>
<td>$269</td>
<td>64,568,004
</td>
<td>$4,166</td>
<td>$52.8 (<a href="/wiki/United_States" title="United States">United States</a>)
</td></tr>
<tr>
<td>Cow's <a href="/wiki/Milk" title="Milk">milk</a>, whole fresh</td>
<td>$238</td>
<td>665,596,536
</td>
<td>$358</td>
<td>$34.7  (United States)
</td></tr>
<tr>
<td><a href="/wiki/Chicken" title="Chicken">Chicken</a>, meat</td>
<td>$192</td>
<td>106,638,508
</td>
<td>$1,800</td>
<td>$27.4 (United States)
</td></tr>
<tr>
<td><a href="/wiki/Maize" title="Maize">Maize</a> (corn)</td>
<td>$191</td>
<td>1,126,990,585
</td>
<td>$169</td>
<td>$61.2 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Wheat" title="Wheat">Wheat</a></td>
<td>$168</td>
<td>748,392,150
</td>
<td>$224</td>
<td>$50.7  (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Soybean" title="Soybean">Soybeans</a></td>
<td>$107</td>
<td>335,613,801
</td>
<td>$319</td>
<td>$40.7 (United States)
</td></tr>
<tr>
<td><a class="mw-redirect" href="/wiki/Eggs_(food)" title="Eggs (food)">Eggs</a>, hen, in shell</td>
<td>$93.6</td>
<td>74,180,272
</td>
<td>$1,262</td>
<td>$26.1 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Potato" title="Potato">Potatoes</a></td>
<td>$92.7</td>
<td>356,952,488
</td>
<td>$260</td>
<td>$32.2 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Vegetable" title="Vegetable">Vegetables</a>, not elsewhere specified</td>
<td>$89.1</td>
<td>292,920,885
</td>
<td>$304</td>
<td>$53.6 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Tomato" title="Tomato">Tomatoes</a></td>
<td>$87.9</td>
<td>178,158,747
</td>
<td>$493</td>
<td>$28.9 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Sugarcane" title="Sugarcane">Sugarcane</a></td>
<td>$87.3</td>
<td>1,874,611,396
</td>
<td>$47</td>
<td>$40.9  (<a href="/wiki/Brazil" title="Brazil">Brazil</a>)
</td></tr>
<tr>
<td><a href="/wiki/Grape" title="Grape">Grapes</a></td>
<td>$67.8</td>
<td>74,089,693
</td>
<td>$915</td>
<td>$14.4 (<a href="/wiki/France" title="France">France</a>)
</td></tr>
<tr>
<td>Seed <a href="/wiki/Cotton" title="Cotton">cotton</a></td>
<td>$56.7</td>
<td>67,622,193
</td>
<td>$838</td>
<td>$21.4 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Water_buffalo" title="Water buffalo">Buffalo</a> milk, whole fresh</td>
<td>$56.4</td>
<td>115,204,379
</td>
<td>$490</td>
<td>$43.1 (<a href="/wiki/India" title="India">India</a>)
</td></tr>
<tr>
<td><a href="/wiki/Cotton" title="Cotton">Cotton</a> lint
</td>
<td>$50.5
</td>
<td>23,274,797
</td>
<td>$2,170
</td>
<td>$18.6 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Apple" title="Apple">Apples</a></td>
<td>$45.9</td>
<td>84,743,988
</td>
<td>$542</td>
<td>$20.8 (Mainland China)
</td></tr>
<tr>
<td><a class="mw-redirect" href="/wiki/Onions" title="Onions">Onions</a>, dry</td>
<td>$42.1</td>
<td>94,838,690
</td>
<td>$444</td>
<td>$23.9 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Sheep" title="Sheep">Sheep</a>, meat</td>
<td>$40.4</td>
<td>9,567,978
</td>
<td>$4,222</td>
<td>$13.8 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Cucumber" title="Cucumber">Cucumbers</a> and gherkins
</td>
<td>$40.2
</td>
<td>79,844,838
</td>
<td>$503
</td>
<td>$29.6 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Garlic" title="Garlic">Garlic</a>
</td>
<td>$39.3
</td>
<td>26,821,718
</td>
<td>$1,465
</td>
<td>$31.5 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Banana" title="Banana">Bananas</a></td>
<td>$38.5</td>
<td>112,627,980
</td>
<td>$342</td>
<td>$8.13 (India)
</td></tr>
<tr>
<td><a href="/wiki/Goat" title="Goat">Goat</a>, meat
</td>
<td>$36.4
</td>
<td>5,794,581
</td>
<td>$6,282
</td>
<td>$25.3 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Elaeis" title="Elaeis">Oil palm fruit</a>
</td>
<td>$35.7
</td>
<td>255,567,218
</td>
<td>$140
</td>
<td>$17.7 (<a href="/wiki/Indonesia" title="Indonesia">Indonesia</a>)
</td></tr>
<tr>
<td><a href="/wiki/Cassava" title="Cassava">Cassava</a> (yuca)</td>
<td>$34.3</td>
<td>288,497,460
</td>
<td>$119</td>
<td>$4.11 (Indonesia)
</td></tr>
<tr>
<td><a href="/wiki/Palm_oil" title="Palm oil">Palm oil</a></td>
<td>$34</td>
<td>58,156,889
</td>
<td>$585</td>
<td>$16.2 (Indonesia)
</td></tr>
<tr>
<td><a class="mw-redirect" href="/wiki/Watermelons" title="Watermelons">Watermelons</a>
</td>
<td>$33.9
</td>
<td>102,414,316
</td>
<td>$331
</td>
<td>$26.1 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Rapeseed" title="Rapeseed">Rapeseed</a></td>
<td>$31.7</td>
<td>68,113,132
</td>
<td>$465</td>
<td>$10.4 (Mainland China)
</td></tr>
<tr>
<td><a class="mw-redirect" href="/wiki/Mangos" title="Mangos">Mangos</a>, <a href="/wiki/Mangosteen" title="Mangosteen">mangosteens</a>, <a class="mw-redirect" href="/wiki/Guavas" title="Guavas">guavas</a></td>
<td>$30.0</td>
<td>49,523,191
</td>
<td>$606</td>
<td>$14.1 (India)
</td></tr>
<tr>
<td><a class="mw-redirect" href="/wiki/Egg_as_food" title="Egg as food">Eggs</a>, other bird, in shell
</td>
<td>$27.9
</td>
<td>6,108,690
</td>
<td>$4,567
</td>
<td>$25.6 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Peanut" title="Peanut">Groundnuts</a>, with shell
</td>
<td>$26.9
</td>
<td>44,543,757
</td>
<td>$604
</td>
<td>$16.1 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Chili_pepper" title="Chili pepper">Chilis</a> and <a class="mw-redirect" href="/wiki/Bell_peppers" title="Bell peppers">peppers</a>, green</td>
<td>$26.3</td>
<td>34,567,250
</td>
<td>$761</td>
<td>$9.95 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Sweet_potato" title="Sweet potato">Sweet potatoes</a></td>
<td>$26.1</td>
<td>89,985,845
</td>
<td>$290</td>
<td>$17.8 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Barley" title="Barley">Barley</a>
</td>
<td>$22.9
</td>
<td>145,906,773
</td>
<td>$157
</td>
<td>$2.08 (<a href="/wiki/Russia" title="Russia">Russia</a>)
</td></tr>
<tr>
<td><a href="/wiki/Orange_(fruit)" title="Orange (fruit)">Oranges</a>
</td>
<td>$22.6
</td>
<td>72,771,146
</td>
<td>$311
</td>
<td>$5.62 (India)
</td></tr>
<tr>
<td><a href="/wiki/Eggplant" title="Eggplant">Eggplants</a> (aubergines)
</td>
<td>$21.6
</td>
<td>51,302,856
</td>
<td>$421
</td>
<td>$16.8 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Olive" title="Olive">Olives</a></td>
<td>$19.9</td>
<td>19,650,821
</td>
<td>$1,013</td>
<td>$5.5 (<a href="/wiki/Greece" title="Greece">Greece</a>)
</td></tr>
<tr>
<td><a href="/wiki/Sunflower_seed" title="Sunflower seed">Sunflower seeds</a>
</td>
<td>$19.4
</td>
<td>47,401,997
</td>
<td>$409
</td>
<td>$4.54 (<a href="/wiki/Ukraine" title="Ukraine">Ukraine</a>)
</td></tr>
<tr>
<td><a href="/wiki/Tangerine" title="Tangerine">Tangerines</a>, <a href="/wiki/Mandarin_orange" title="Mandarin orange">mandarins</a>, <a href="/wiki/Clementine" title="Clementine">clementines</a>, <a href="/wiki/Citrus_unshiu" title="Citrus unshiu">satsumas</a>
</td>
<td>$19.1
</td>
<td>32,304,732
</td>
<td>$591
</td>
<td>$12.2 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Cabbage" title="Cabbage">Cabbages</a> and other <a href="/wiki/Brassica" title="Brassica">brassicas</a>
</td>
<td>$19.1
</td>
<td>69,790,058
</td>
<td>$274
</td>
<td>$9.3 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Spinach" title="Spinach">Spinach</a>
</td>
<td>$18
</td>
<td>26,763,044
</td>
<td>$673
</td>
<td>$15.4 (Mainland China)
</td></tr>
<tr>
<td><a class="mw-redirect" href="/wiki/Strawberries" title="Strawberries">Strawberries</a>
</td>
<td>$17.7
</td>
<td>7,901,882
</td>
<td>$2,240
</td>
<td>$6.49 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Peach" title="Peach">Peaches</a>, <a class="mw-redirect" href="/wiki/Nectarines" title="Nectarines">nectarines</a></td>
<td>$17.1</td>
<td>24,040,295
</td>
<td>$711</td>
<td>$9.98 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Tobacco" title="Tobacco">Tobacco</a>, unmanufactured
</td>
<td>$16.2
</td>
<td>6,361,725
</td>
<td>$2,546
</td>
<td>$8.27 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Coffee" title="Coffee">Coffee</a>, green</td>
<td>$16.1</td>
<td>9,353,937
</td>
<td>$1,721</td>
<td>$6.75 (Brazil)
</td></tr>
<tr>
<td><a href="/wiki/Lettuce" title="Lettuce">Lettuce</a>, <a href="/wiki/Chicory" title="Chicory">chicory</a></td>
<td>$15.7</td>
<td>27,440,987
</td>
<td>$572</td>
<td>$8.33 (Mainland China)
</td></tr>
<tr>
<td><a class="mw-redirect" href="/wiki/Rubber" title="Rubber">Rubber</a>, natural</td>
<td>$15.3</td>
<td>13,449,190
</td>
<td>$1,138</td>
<td>$6.19 (<a href="/wiki/Thailand" title="Thailand">Thailand</a>)
</td></tr>
<tr>
<td><a href="/wiki/Tea" title="Tea">Tea</a></td>
<td>$15.2</td>
<td>5,859,841
</td>
<td>$2,594</td>
<td>$11.3 (Mainland China)
</td></tr>
<tr>
<td><a href="/wiki/Pea" title="Pea">Peas</a>, green</td>
<td>$14.7</td>
<td>19,854,943
</td>
<td>$740</td>
<td>$9.68 (Mainland China)
</td></tr></tbody></table>

In [14]:
titles = table.find_all('th')
print(titles)

[<th>Crop or Livestock</th>, <th>Global gross production value in billion US$</th>, <th data-sort-type="number">Global production in metric tons
</th>, <th>Global production in US$/metric ton</th>, <th>Country with highest gross production value in billion USD
</th>]

In [22]:
[clean_title.text.strip() for clean_title in titles]

['Crop or Livestock',
 'Global gross production value in billion US$',
 'Global production in metric tons',
 'Global production in US$/metric ton',
 'Country with highest gross production value in billion USD']

In [26]:
clean_titles = [clean_title.text.strip() for clean_title in titles]
print(clean_titles)

['Crop or Livestock', 'Global gross production value in billion US$', 'Global production in metric tons', 'Global production in US$/metric ton', 'Country with highest gross production value in billion USD']

In [29]:
import pandas as pd
df = pd.DataFrame(columns = clean_titles)
df

Empty DataFrame
Columns: [Crop or Livestock, Global gross production value in billion US$, Global production in metric tons, Global production in US$/metric ton, Country with highest gross production value in billion USD]
Index: []

In [34]:
column_data = table.find_all('tr')

In [36]:
#Addition of index number on the loop to avoid the top blank bracket
for rows in column_data[1:]:
    Rows = rows.find_all('td')
    DATA = [Data.text.strip() for Data in Rows]
    print(DATA)

['Rice, paddy', '$332', '751,885,117', '$442', '$117 (Mainland China)']
['Pig, meat', '$280', '118,956,327', '$2,354', '$167 (Mainland China)']
['Cattle, meat', '$269', '64,568,004', '$4,166', '$52.8 (United States)']
["Cow's milk, whole fresh", '$238', '665,596,536', '$358', '$34.7  (United States)']
['Chicken, meat', '$192', '106,638,508', '$1,800', '$27.4 (United States)']
['Maize (corn)', '$191', '1,126,990,585', '$169', '$61.2 (Mainland China)']
['Wheat', '$168', '748,392,150', '$224', '$50.7  (Mainland China)']
['Soybeans', '$107', '335,613,801', '$319', '$40.7 (United States)']
['Eggs, hen, in shell', '$93.6', '74,180,272', '$1,262', '$26.1 (Mainland China)']
['Potatoes', '$92.7', '356,952,488', '$260', '$32.2 (Mainland China)']
['Vegetables, not elsewhere specified', '$89.1', '292,920,885', '$304', '$53.6 (Mainland China)']
['Tomatoes', '$87.9', '178,158,747', '$493', '$28.9 (Mainland China)']
['Sugarcane', '$87.3', '1,874,611,396', '$47', '$40.9  (Brazil)']
['Grapes', '$67.8', '74,089,693', '$915', '$14.4 (France)']
['Seed cotton', '$56.7', '67,622,193', '$838', '$21.4 (Mainland China)']
['Buffalo milk, whole fresh', '$56.4', '115,204,379', '$490', '$43.1 (India)']
['Cotton lint', '$50.5', '23,274,797', '$2,170', '$18.6 (Mainland China)']
['Apples', '$45.9', '84,743,988', '$542', '$20.8 (Mainland China)']
['Onions, dry', '$42.1', '94,838,690', '$444', '$23.9 (Mainland China)']
['Sheep, meat', '$40.4', '9,567,978', '$4,222', '$13.8 (Mainland China)']
['Cucumbers and gherkins', '$40.2', '79,844,838', '$503', '$29.6 (Mainland China)']
['Garlic', '$39.3', '26,821,718', '$1,465', '$31.5 (Mainland China)']
['Bananas', '$38.5', '112,627,980', '$342', '$8.13 (India)']
['Goat, meat', '$36.4', '5,794,581', '$6,282', '$25.3 (Mainland China)']
['Oil palm fruit', '$35.7', '255,567,218', '$140', '$17.7 (Indonesia)']
['Cassava (yuca)', '$34.3', '288,497,460', '$119', '$4.11 (Indonesia)']
['Palm oil', '$34', '58,156,889', '$585', '$16.2 (Indonesia)']
['Watermelons', '$33.9', '102,414,316', '$331', '$26.1 (Mainland China)']
['Rapeseed', '$31.7', '68,113,132', '$465', '$10.4 (Mainland China)']
['Mangos, mangosteens, guavas', '$30.0', '49,523,191', '$606', '$14.1 (India)']
['Eggs, other bird, in shell', '$27.9', '6,108,690', '$4,567', '$25.6 (Mainland China)']
['Groundnuts, with shell', '$26.9', '44,543,757', '$604', '$16.1 (Mainland China)']
['Chilis and peppers, green', '$26.3', '34,567,250', '$761', '$9.95 (Mainland China)']
['Sweet potatoes', '$26.1', '89,985,845', '$290', '$17.8 (Mainland China)']
['Barley', '$22.9', '145,906,773', '$157', '$2.08 (Russia)']
['Oranges', '$22.6', '72,771,146', '$311', '$5.62 (India)']
['Eggplants (aubergines)', '$21.6', '51,302,856', '$421', '$16.8 (Mainland China)']
['Olives', '$19.9', '19,650,821', '$1,013', '$5.5 (Greece)']
['Sunflower seeds', '$19.4', '47,401,997', '$409', '$4.54 (Ukraine)']
['Tangerines, mandarins, clementines, satsumas', '$19.1', '32,304,732', '$591', '$12.2 (Mainland China)']
['Cabbages and other brassicas', '$19.1', '69,790,058', '$274', '$9.3 (Mainland China)']
['Spinach', '$18', '26,763,044', '$673', '$15.4 (Mainland China)']
['Strawberries', '$17.7', '7,901,882', '$2,240', '$6.49 (Mainland China)']
['Peaches, nectarines', '$17.1', '24,040,295', '$711', '$9.98 (Mainland China)']
['Tobacco, unmanufactured', '$16.2', '6,361,725', '$2,546', '$8.27 (Mainland China)']
['Coffee, green', '$16.1', '9,353,937', '$1,721', '$6.75 (Brazil)']
['Lettuce, chicory', '$15.7', '27,440,987', '$572', '$8.33 (Mainland China)']
['Rubber, natural', '$15.3', '13,449,190', '$1,138', '$6.19 (Thailand)']
['Tea', '$15.2', '5,859,841', '$2,594', '$11.3 (Mainland China)']
['Peas, green', '$14.7', '19,854,943', '$740', '$9.68 (Mainland China)']

In [37]:
for rows in column_data[1:]:
    Rows = rows.find_all('td')
    DATA = [Data.text.strip() for Data in Rows]
    
    length =  len(df)
    df.loc[length] = DATA

In [38]:
df

,Crop or Livestock,Global gross production value in billion US$,Global production in metric tons,Global production in US$/metric ton,Country with highest gross production value in billion USD
0,"Rice, paddy",$332,"751,885,117",$442,$117 (Mainland China)
1,"Pig, meat",$280,"118,956,327","$2,354",$167 (Mainland China)
2,"Cattle, meat",$269,"64,568,004","$4,166",$52.8 (United States)
3,"Cow's milk, whole fresh",$238,"665,596,536",$358,$34.7 (United States)
4,"Chicken, meat",$192,"106,638,508","$1,800",$27.4 (United States)
5,Maize (corn),$191,"1,126,990,585",$169,$61.2 (Mainland China)
6,Wheat,$168,"748,392,150",$224,$50.7 (Mainland China)
7,Soybeans,$107,"335,613,801",$319,$40.7 (United States)
8,"Eggs, hen, in shell",$93.6,"74,180,272","$1,262",$26.1 (Mainland China)
9,Potatoes,$92.7,"356,952,488",$260,$32.2 (Mainland China)
10,"Vegetables, not elsewhere specified",$89.1,"292,920,885",$304,$53.6 (Mainland China)
11,Tomatoes,$87.9,"178,158,747",$493,$28.9 (Mainland China)
12,Sugarcane,$87.3,"1,874,611,396",$47,$40.9 (Brazil)
13,Grapes,$67.8,"74,089,693",$915,$14.4 (France)
14,Seed cotton,$56.7,"67,622,193",$838,$21.4 (Mainland China)
15,"Buffalo milk, whole fresh",$56.4,"115,204,379",$490,$43.1 (India)
16,Cotton lint,$50.5,"23,274,797","$2,170",$18.6 (Mainland China)
17,Apples,$45.9,"84,743,988",$542,$20.8 (Mainland China)
18,"Onions, dry",$42.1,"94,838,690",$444,$23.9 (Mainland China)
19,"Sheep, meat",$40.4,"9,567,978","$4,222",$13.8 (Mainland China)
20,Cucumbers and gherkins,$40.2,"79,844,838",$503,$29.6 (Mainland China)
21,Garlic,$39.3,"26,821,718","$1,465",$31.5 (Mainland China)
22,Bananas,$38.5,"112,627,980",$342,$8.13 (India)
23,"Goat, meat",$36.4,"5,794,581","$6,282",$25.3 (Mainland China)
24,Oil palm fruit,$35.7,"255,567,218",$140,$17.7 (Indonesia)
25,Cassava (yuca),$34.3,"288,497,460",$119,$4.11 (Indonesia)
26,Palm oil,$34,"58,156,889",$585,$16.2 (Indonesia)
27,Watermelons,$33.9,"102,414,316",$331,$26.1 (Mainland China)
28,Rapeseed,$31.7,"68,113,132",$465,$10.4 (Mainland China)
29,"Mangos, mangosteens, guavas",$30.0,"49,523,191",$606,$14.1 (India)
30,"Eggs, other bird, in shell",$27.9,"6,108,690","$4,567",$25.6 (Mainland China)
31,"Groundnuts, with shell",$26.9,"44,543,757",$604,$16.1 (Mainland China)
32,"Chilis and peppers, green",$26.3,"34,567,250",$761,$9.95 (Mainland China)
33,Sweet potatoes,$26.1,"89,985,845",$290,$17.8 (Mainland China)
34,Barley,$22.9,"145,906,773",$157,$2.08 (Russia)
35,Oranges,$22.6,"72,771,146",$311,$5.62 (India)
36,Eggplants (aubergines),$21.6,"51,302,856",$421,$16.8 (Mainland China)
37,Olives,$19.9,"19,650,821","$1,013",$5.5 (Greece)
38,Sunflower seeds,$19.4,"47,401,997",$409,$4.54 (Ukraine)
39,"Tangerines, mandarins, clementines, satsumas",$19.1,"32,304,732",$591,$12.2 (Mainland China)
40,Cabbages and other brassicas,$19.1,"69,790,058",$274,$9.3 (Mainland China)
41,Spinach,$18,"26,763,044",$673,$15.4 (Mainland China)
42,Strawberries,$17.7,"7,901,882","$2,240",$6.49 (Mainland China)
43,"Peaches, nectarines",$17.1,"24,040,295",$711,$9.98 (Mainland China)
44,"Tobacco, unmanufactured",$16.2,"6,361,725","$2,546",$8.27 (Mainland China)
45,"Coffee, green",$16.1,"9,353,937","$1,721",$6.75 (Brazil)
46,"Lettuce, chicory",$15.7,"27,440,987",$572,$8.33 (Mainland China)
47,"Rubber, natural",$15.3,"13,449,190","$1,138",$6.19 (Thailand)
48,Tea,$15.2,"5,859,841","$2,594",$11.3 (Mainland China)
49,"Peas, green",$14.7,"19,854,943",$740,$9.68 (Mainland China)

In [39]:
df.to_csv(r'C:\Users\Reuben Yohanna Vandi\Pictures\python\List of the most valuable crops and livestocks products.cvs')

In [40]:
#To remove defualt index column on dataset
df.to_csv(r'C:\Users\Reuben Yohanna Vandi\Pictures\python\List of the most valuable crops and livestocks products.cvs', index = False)